"""Generate the frontend's CSV schema fields from the backend contract."""

import json
from pathlib import Path

from app.contracts.customization import IMPORT_FIELDS

OUTPUT = Path(__file__).resolve().parents[2] / "frontend/src/api/importSchemas.ts"


def render() -> str:
    types = " | ".join(json.dumps(schema) for schema in IMPORT_FIELDS)
    fields = {
        schema: {"all": sorted(all_fields), "required": sorted(required)}
        for schema, (all_fields, required) in IMPORT_FIELDS.items()
    }
    return (
        "// Generated by backend/scripts/export_import_ui.py.\n"
        f"export type ImportSchema = {types};\n\n"
        "export const IMPORT_FIELDS: Record<ImportSchema, { all: string[]; required: string[] }> = "
        + json.dumps(fields, indent=2)
        + ";\n"
    )


if __name__ == "__main__":
    OUTPUT.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.name}")
