// Generated by backend/scripts/export_import_ui.py.
export type ImportSchema = "bank_statement_v1" | "payables_register_v1" | "purchase_orders_v1" | "stock_v1" | "payroll_v1" | "marketing_spend_v1" | "marketplace_payouts_v1" | "sales_pipeline_v1";

export const IMPORT_FIELDS: Record<ImportSchema, { all: string[]; required: string[] }> = {
  "bank_statement_v1": {
    "all": [
      "balance",
      "counterparty",
      "credit",
      "date",
      "debit",
      "description",
      "reference"
    ],
    "required": [
      "credit",
      "date",
      "debit",
      "description"
    ]
  },
  "payables_register_v1": {
    "all": [
      "amount",
      "bank_account",
      "bill_id",
      "currency",
      "due_date",
      "fx_rate",
      "status",
      "supplier"
    ],
    "required": [
      "amount",
      "bill_id",
      "currency",
      "due_date",
      "supplier"
    ]
  },
  "purchase_orders_v1": {
    "all": [
      "amount",
      "currency",
      "expected_delivery",
      "expected_payment",
      "fx_rate",
      "po_no",
      "status",
      "supplier"
    ],
    "required": [
      "amount",
      "currency",
      "expected_delivery",
      "expected_payment",
      "po_no",
      "supplier"
    ]
  },
  "stock_v1": {
    "all": [
      "lead_time_days",
      "name",
      "on_hand",
      "reorder_level",
      "sku",
      "snapshot_date",
      "unit_cost"
    ],
    "required": [
      "name",
      "on_hand",
      "sku",
      "snapshot_date",
      "unit_cost"
    ]
  },
  "payroll_v1": {
    "all": [
      "employee",
      "employer_contribution",
      "gross",
      "pay_date",
      "period",
      "status"
    ],
    "required": [
      "employee",
      "employer_contribution",
      "gross",
      "pay_date",
      "period"
    ]
  },
  "marketing_spend_v1": {
    "all": [
      "attributed_revenue",
      "campaign",
      "channel",
      "period_end",
      "period_start",
      "reference",
      "spend"
    ],
    "required": [
      "campaign",
      "channel",
      "period_end",
      "period_start",
      "reference",
      "spend"
    ]
  },
  "marketplace_payouts_v1": {
    "all": [
      "fees",
      "gross",
      "net",
      "payout_date",
      "platform",
      "reference",
      "status"
    ],
    "required": [
      "fees",
      "gross",
      "net",
      "payout_date",
      "platform",
      "reference"
    ]
  },
  "sales_pipeline_v1": {
    "all": [
      "amount",
      "customer",
      "expected_payment_date",
      "probability",
      "reference",
      "stage"
    ],
    "required": [
      "amount",
      "customer",
      "expected_payment_date",
      "reference",
      "stage"
    ]
  }
};
